const RESPONSE_TYPE_CONFIG = {
    TAO: "TAO",
    CARD: "CARD",
    SKILL: "SKILL",
    CARD_BOARD: "CARD_BOARD",
    FAN_JIAN_BOARD: "FAN_JIAN_BOARD",
    WUXIE: "WUXIE",
}


exports.RESPONSE_TYPE_CONFIG = RESPONSE_TYPE_CONFIG;
