const RESPONSE_TYPE_CONFIG = {
    TAO: "TAO",
    SHAN: "SHAN",
    SKILL: "SKILL",
    WUXIE: "WUXIE",
    WEAPON: "WEAPON",
    SCROLL: "SCROLL"
}


exports.RESPONSE_TYPE_CONFIG = RESPONSE_TYPE_CONFIG;
